### ISSUE TITLE
Incompatible libnoise path on Arch Linux

### ISSUE THREAD

**Issue by offa** [tarTG/RTplatec#6]
The compilation on Arch Linux fails due a different include path of **_libnoise**_ (integration test off).
### Used path [noiseutils.cpp](https://github.com/tarTG/RTplatec/blob/master/3rdParty/libNoiseUtils/noiseutils.cpp#L25):

```
#include <libnoise/interp.h>
```
### Installation path [Ubuntu](http://packages.ubuntu.com/precise/libnoise-dev) ([file list](http://packages.ubuntu.com/precise/amd64/libnoise-dev/filelist)):

```
/usr/include/libnoise/interp.h
```
### Installation path [Arch Linux](https://www.archlinux.org/packages/community/x86_64/libnoise/) ([file list](https://www.archlinux.org/packages/community/x86_64/libnoise/files/)):

```
usr/include/noise/interp.h
```
## Workaround

Cmake detects the correct path:

```
LIBNOISE_INCLUDE_DIR: /usr/include/noise
```

As a workaround I changed all _libnoise_ includes from eg.

```
#include <libnoise/interp.h>
```

to

```
#include <interp.h>
```

This solved the problem.

**Comment by tarTG** [comment]
Fixed ( see commit 333ce68)
