### ISSUE TITLE
Building integration test fails by GLFW

### ISSUE THREAD

**Issue by offa** [tarTG/RTplatec#7]
Building with integration test enabled fails by following Cmake error:

```
CMake Error at test/integration/CMakeLists.txt:23 (include_directories):
  include_directories given empty-string as include directory
```
It look likes the `GLFW_INCLUDE_DIRS` variable is not populated; whereby the include mentioned by the error expands to an empty string. Printing out the variable confirmed that. GLFW is installed (glfw x11<sup>i)</sup> 3.2.1).

### Workaround

As a workaround I replaced these lines:

```
find_package(PkgConfig REQUIRED)
pkg_search_module(GLFW REQUIRED glfw3)

…
include_directories("${GLFW_INCLUDE_DIRS}" )
```

by this those:

```
find_package(PkgConfig REQUIRED)

include_directories("${GLFW_INCLUDE_DIR}") ### Trailing 'S' removed
```

This compiled the integration test successfully.

------------------------------
<sup>i)</sup> Wayland glfw not tested.

**Comment by tarTG** [comment]
Should be fixed now 39f2b7cf845c01710953a43ba47f0aa192c476eb
