### ISSUE TITLE
Init failure should return an errorcode and more information

### ISSUE THREAD

**Issue by offa** [tarTG/RTplatec#8]
If [initialization fails](https://github.com/tarTG/RTplatec/blob/master/test/integration/main.cpp#L132), this should return an errorcode instead of `0` (= exit successfully). In addition there's not much info about the cause of the error.

**Comment by offa** [comment]
Possible: http://www.glfw.org/docs/latest/intro.html#error_handling

**Comment by tarTG** [comment]
Will be done in next Release.
In the meantime, you can check your OpenGL version in the Terminal.

```
sudo apt-get install mesa-utils
glxinfo | grep "OpenGL version"
```

if the Version is lower than 4.0, the OpenGL context can not be started. This is required for using the Shaders.
